version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  apply:
    docker:
      - image: hashicorp/terraform:1.6.6
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y curl unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

      - run:
    name: Setup AWS Credentials
    command: |
      mkdir -p ~/.aws
      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials


      - run:
          name: Terraform Init + Plan + Apply
          command: |
            cd envs/dev
            terraform init
            terraform plan
            terraform apply -auto-approve