version: 2.1

jobs:
  terraform-plan:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install jq
          command: sudo apt-get update && sudo apt-get install -y jq

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

      - run:
          name: Assume Role with OIDC
          command: |
            export AWS_ROLE_ARN="arn:aws:iam::265753586529:role/CircleCi-Role"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/web_identity_token"
            export AWS_DEFAULT_REGION="ap-south-1"
            curl -s -o "$AWS_WEB_IDENTITY_TOKEN_FILE" "$CIRCLE_OIDC_TOKEN"
            creds=$(aws sts assume-role-with-web-identity \
              --role-arn "$AWS_ROLE_ARN" \
              --role-session-name "CircleCISession" \
              --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE \
              --duration-seconds 3600)
            export AWS_ACCESS_KEY_ID=$(echo $creds | jq -r '.Credentials.AccessKeyId')
            export AWS_SECRET_ACCESS_KEY=$(echo $creds | jq -r '.Credentials.SecretAccessKey')
            export AWS_SESSION_TOKEN=$(echo $creds | jq -r '.Credentials.SessionToken')

      - run:
          name: Terraform Init + Plan
          command: |
            cd envs/dev
            terraform init
            terraform plan -out=tfplan

        workflows:
          terraform-workflow:
            jobs:
              - terraform-plan