version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.6.6
    environment:
      AWS_REGION: ap-south-1
    steps:
      - checkout

      - run:
          name: Set AWS Credentials
          command: echo "Using CircleCI environment variables for AWS credentials"

      - terraform/init:
          path: envs/dev

      - terraform/plan:
          path: envs/dev

      - terraform/apply:
          path: envs/dev

workflows:
  terraform-workflow:
    jobs:
      - terraform-apply 
