version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  terraform-init-and-plan:
    docker:
      - image: hashicorp/terraform:1.6.6
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y curl unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

      - run:
          name: Assume Role with OIDC
          command: |
            export AWS_ROLE_ARN="arn:aws:iam::265753586529:role/CircleCi-Role"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/web_identity_token"
            curl -s -o $AWS_WEB_IDENTITY_TOKEN_FILE "$CIRCLE_OIDC_TOKEN"
            export AWS_DEFAULT_REGION="ap-south-1"

      - run:
          name: Terraform Init and Plan
          command: |
            cd envs/dev
            terraform init
            terraform plan -out=tfplan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.6.6
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y curl unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

      - run:
          name: Assume Role with OIDC
          command: |
            export AWS_ROLE_ARN="arn:aws:iam::265753586529:role/CircleCi-Role"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/web_identity_token"
            curl -s -o $AWS_WEB_IDENTITY_TOKEN_FILE "$CIRCLE_OIDC_TOKEN"
            export AWS_DEFAULT_REGION="ap-south-1"

      - run:
          name: Terraform Apply
          command: |
            cd envs/dev
            terraform apply -auto-approve tfplan

workflows:
  terraform-workflow:
    jobs:
      - terraform-init-and-plan
      - hold-for-approval:
          type: approval
          requires:
            - terraform-init-and-plan
      - terraform-apply:
          requires:
            - hold-for-approval
