version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  terraform-init-and-plan:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update && sudo apt-get install -y terraform

      - run:
          name: Assume Role with OIDC
          command: |
            sudo apt-get install -y curl unzip
            export AWS_ROLE_ARN="arn:aws:iam::265753586529:role/CircleCi-Role"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/web_identity_token"
            curl -s -o $AWS_WEB_IDENTITY_TOKEN_FILE "$CIRCLE_OIDC_TOKEN"
            export AWS_DEFAULT_REGION="ap-south-1"

      - run:
          name: Terraform Init and Plan
          command: |
            cd envs/dev
            terraform init
            terraform plan -out=tfplan
