version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  apply:
    docker:
      - image: hashicorp/terraform:1.6.6
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y curl unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

      - run:
    name: Assume Role with OIDC
    command: |
      export AWS_ROLE_ARN="arn:aws:iam::265753586529:role/CircleCi-Role"
      export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/web_identity_token"
      curl -s -o $AWS_WEB_IDENTITY_TOKEN_FILE "$CIRCLE_OIDC_TOKEN"
      export AWS_DEFAULT_REGION="ap-south-1"


      - run:
          name: Terraform Init + Plan + Apply
          command: |
            cd envs/dev
            terraform init
            terraform plan
            terraform apply -auto-approve